services:
  - type: web
    name: mindmate
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGODB_CONNECTION_STRING
        fromService:
          type: web
          name: mindmate
          envVarKey: MONGODB_CONNECTION_STRING
      - key: COSMOS_DATABASE
        value: mindmate
      - key: AI_API_URL
        value: https://aiengine-sable.vercel.app
      - key: DB_TYPE
        value: mongodb